{% set name = "healpix" %}
{% set version = "2024.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/healpix-{{ version }}.tar.gz
  sha256: 3462c187206aad701f90f1a7e0e81cabd96974034d9e2befdc1c26721267a777

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - healpix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ntessore/healpix
  summary: Python package for HEALPix discretisation of the sphere
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - beckermr
