{% set name = "healpix" %}
{% set version = "2025.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/healpix-{{ version }}.tar.gz
  sha256: 733f16f30c15d911c8209f4045f0b0934e5fcafa63b8b39d62e425a036adccea

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - healpix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ntessore/healpix
  summary: Python package for HEALPix discretisation of the sphere
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - beckermr
