{% set name = "healpix" %}
{% set version = "2023.1.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/healpix-{{ version }}.tar.gz
  sha256: 254f00520724ec5f17dbed3393e3bf17c892b7e95ac6df52ef9a7f6b68e384e1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - healpix
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ntessore/healpix
  summary: Python package for HEALPix discretisation of the sphere
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - beckermr
